/* Generated By:JavaCC: Do not edit this line. MiniLangParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniLangParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAM = 1;
  /** RegularExpression Id. */
  int VAR = 2;
  /** RegularExpression Id. */
  int FUNC = 3;
  /** RegularExpression Id. */
  int PROC = 4;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int IF = 6;
  /** RegularExpression Id. */
  int ELSE = 7;
  /** RegularExpression Id. */
  int WHILE = 8;
  /** RegularExpression Id. */
  int FOR = 9;
  /** RegularExpression Id. */
  int RETURN = 10;
  /** RegularExpression Id. */
  int PRINT = 11;
  /** RegularExpression Id. */
  int INT = 12;
  /** RegularExpression Id. */
  int FLOAT = 13;
  /** RegularExpression Id. */
  int BOOLEAN = 14;
  /** RegularExpression Id. */
  int TRUE = 15;
  /** RegularExpression Id. */
  int FALSE = 16;
  /** RegularExpression Id. */
  int LEN = 17;
  /** RegularExpression Id. */
  int PLUS = 18;
  /** RegularExpression Id. */
  int MINUS = 19;
  /** RegularExpression Id. */
  int MULT = 20;
  /** RegularExpression Id. */
  int DIV = 21;
  /** RegularExpression Id. */
  int MOD = 22;
  /** RegularExpression Id. */
  int ASSIGN = 23;
  /** RegularExpression Id. */
  int PLUSASSIGN = 24;
  /** RegularExpression Id. */
  int MINUSASSIGN = 25;
  /** RegularExpression Id. */
  int MULTASSIGN = 26;
  /** RegularExpression Id. */
  int DIVASSIGN = 27;
  /** RegularExpression Id. */
  int EQ = 28;
  /** RegularExpression Id. */
  int NE = 29;
  /** RegularExpression Id. */
  int LE = 30;
  /** RegularExpression Id. */
  int LT = 31;
  /** RegularExpression Id. */
  int GE = 32;
  /** RegularExpression Id. */
  int GT = 33;
  /** RegularExpression Id. */
  int AND = 34;
  /** RegularExpression Id. */
  int OR = 35;
  /** RegularExpression Id. */
  int NOT = 36;
  /** RegularExpression Id. */
  int IDENTIFIER = 37;
  /** RegularExpression Id. */
  int INTEGER = 38;
  /** RegularExpression Id. */
  int FLOAT_LIT = 39;
  /** RegularExpression Id. */
  int LICOM = 40;
  /** RegularExpression Id. */
  int PACOM = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"program\"",
    "\"var\"",
    "\"func\"",
    "\"proc\"",
    "\"main\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"return\"",
    "\"print\"",
    "\"int\"",
    "\"float\"",
    "\"boolean\"",
    "\"true\"",
    "\"false\"",
    "\"len\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\"<\"",
    "\">=\"",
    "\">\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "<IDENTIFIER>",
    "<INTEGER>",
    "<FLOAT_LIT>",
    "<LICOM>",
    "<PACOM>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
