/* MiniLangParser.java */
/* Generated By:JavaCC: Do not edit this line. MiniLangParser.java */
import java.io.*;
import java.util.*;
import ast.*;

public class MiniLangParser implements MiniLangParserConstants {
  public static void main(String[] args) throws Exception {
    MiniLangParser parser = new MiniLangParser(System.in);
    ProgramNode prog = parser.prog();
    System.out.println("Parsing r\u00e9ussi !");
    prog.execute(null);  // Interprétation
  }

/* ===== GRAMMAIRE ===== */

// prog = "program", identifier, ";", [ vars_globales ], { fonc | proc }, main ;
  final public ProgramNode prog() throws ParseException {Token name;
  List<VarDeclNode> globalVars = new ArrayList<>();

  // On utilise une liste générique ou parente pour accepter Fonctions ET Procédures
  List<FunctionNode> functions = new ArrayList<>();
  MainNode main;
  FunctionNode f;
  ProcNode p;
    jj_consume_token(PROGRAM);
    name = jj_consume_token(IDENTIFIER);
    jj_consume_token(45);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VAR:{
      globalVars = vars_globales();
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      ;
    }
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FUNC:
      case PROC:{
        ;
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FUNC:{
        f = fonc();
functions.add(f);
        break;
        }
      case PROC:{
        p = proc();
functions.add((FunctionNode)p);
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    main = main();
    jj_consume_token(0);
{if ("" != null) return new ProgramNode(name.image, globalVars, functions, main);}
    throw new Error("Missing return statement in function");
}

// vars_globales = "var", { decl_var } ;
  final public List<VarDeclNode> vars_globales() throws ParseException {List<VarDeclNode> vars = new ArrayList<>();
  VarDeclNode v;
    jj_consume_token(VAR);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT:
      case FLOAT:
      case BOOLEAN:{
        ;
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        break label_2;
      }
      v = decl_var();
vars.add(v);
    }
{if ("" != null) return vars;}
    throw new Error("Missing return statement in function");
}

// main = "main", "{", { decl_var }, { instr }, "}" ;
  final public MainNode main() throws ParseException {List<VarDeclNode> vars = new ArrayList<>();
  List<InstrNode> instrs = new ArrayList<>();
  VarDeclNode v;
  InstrNode i;
    jj_consume_token(MAIN);
    jj_consume_token(46);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT:
      case FLOAT:
      case BOOLEAN:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_3;
      }
      v = decl_var();
vars.add(v);
    }
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF:
      case WHILE:
      case RETURN:
      case PRINT:
      case IDENTIFIER:
      case 45:
      case 46:{
        ;
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        break label_4;
      }
      i = instr();
instrs.add(i);
    }
    jj_consume_token(47);
{if ("" != null) return new MainNode(vars, instrs);}
    throw new Error("Missing return statement in function");
}

// type = "int" | "float" | "boolean", [ array_dim ] ;
  final public String type_() throws ParseException {String baseType;
  String arrayDim = "";
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:{
      jj_consume_token(INT);
baseType = "int";
      break;
      }
    case FLOAT:{
      jj_consume_token(FLOAT);
baseType = "float";
      break;
      }
    case BOOLEAN:{
      jj_consume_token(BOOLEAN);
baseType = "boolean";
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 48:{
      arrayDim = array_dim();
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      ;
    }
{if ("" != null) return baseType + arrayDim;}
    throw new Error("Missing return statement in function");
}

// array_dim = "[", [ integer ], "]" ;
  final public String array_dim() throws ParseException {Token size = null;
    jj_consume_token(48);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTEGER:{
      size = jj_consume_token(INTEGER);
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      ;
    }
    jj_consume_token(49);
{if ("" != null) return size != null ? "[" + size.image + "]" : "[]";}
    throw new Error("Missing return statement in function");
}

// decl_var = type, identifier, [ "=" exp ], ";" ;
  final public VarDeclNode decl_var() throws ParseException {String type;
  Token name;
  Node initValue = null;
    type = type_();
    name = jj_consume_token(IDENTIFIER);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ASSIGN:{
      jj_consume_token(ASSIGN);
      initValue = exp();
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      ;
    }
    jj_consume_token(45);
{if ("" != null) return new VarDeclNode(type, name.image, initValue);}
    throw new Error("Missing return statement in function");
}

// instr = assign | appel_fonc | if | while | return | print | block | ";" ;
  final public InstrNode instr() throws ParseException {InstrNode n;
    if (jj_2_1(2)) {
      n = assign();
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 45:{
        jj_consume_token(45);
n = new EmptyInstrNode();
        break;
        }
      case IF:{
        n = if_();
        break;
        }
      case WHILE:{
        n = while_();
        break;
        }
      case RETURN:{
        n = return_();
        break;
        }
      case PRINT:{
        n = print_();
        break;
        }
      case 46:{
        n = block();
        break;
        }
      case IDENTIFIER:{
        n = appel_proc();
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return n;}
    throw new Error("Missing return statement in function");
}

// assign = lvalue, assign_op, exp, ";" ;
  final public AssignNode assign() throws ParseException {LValueNode lval;
  String op;
  Node exp;
    lval = lvalue();
    op = assign_op();
    exp = exp();
    jj_consume_token(45);
{if ("" != null) return new AssignNode(lval, op, exp);}
    throw new Error("Missing return statement in function");
}

  final public String assign_op() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ASSIGN:{
      jj_consume_token(ASSIGN);
{if ("" != null) return "=";}
      break;
      }
    case PLUSASSIGN:{
      jj_consume_token(PLUSASSIGN);
{if ("" != null) return "+=";}
      break;
      }
    case MINUSASSIGN:{
      jj_consume_token(MINUSASSIGN);
{if ("" != null) return "-=";}
      break;
      }
    case MULTASSIGN:{
      jj_consume_token(MULTASSIGN);
{if ("" != null) return "*=";}
      break;
      }
    case DIVASSIGN:{
      jj_consume_token(DIVASSIGN);
{if ("" != null) return "/=";}
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

// Expressions avec opérateurs (respect de la priorité)
  final public Node exp() throws ParseException {Node result;
    result = exp_logi();
{if ("" != null) return result;}
    throw new Error("Missing return statement in function");
}

  final public Node exp_logi() throws ParseException {Node left, right;
    left = exp_comp();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OR:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_5;
      }
      jj_consume_token(OR);
      right = exp_comp();
left = new BinOpNode(left, "||", right);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  final public Node exp_comp() throws ParseException {Node left, right;
  String op;
    left = exp_ari();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQ:
      case NE:
      case LE:
      case LT:
      case GE:
      case GT:{
        ;
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        break label_6;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case GT:{
        jj_consume_token(GT);
op = ">";
        break;
        }
      case LT:{
        jj_consume_token(LT);
op = "<";
        break;
        }
      case GE:{
        jj_consume_token(GE);
op = ">=";
        break;
        }
      case LE:{
        jj_consume_token(LE);
op = "<=";
        break;
        }
      case EQ:{
        jj_consume_token(EQ);
op = "==";
        break;
        }
      case NE:{
        jj_consume_token(NE);
op = "!=";
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = exp_ari();
left = new BinOpNode(left, op, right);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  final public Node exp_ari() throws ParseException {Node left, right;
  String op;
    left = term();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:{
        ;
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        break label_7;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        jj_consume_token(PLUS);
op = "+";
        break;
        }
      case MINUS:{
        jj_consume_token(MINUS);
op = "-";
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = term();
left = new BinOpNode(left, op, right);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  final public Node term() throws ParseException {Node left, right;
  String op;
    left = factor();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULT:
      case DIV:{
        ;
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        break label_8;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULT:{
        jj_consume_token(MULT);
op = "*";
        break;
        }
      case DIV:{
        jj_consume_token(DIV);
op = "/";
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = factor();
left = new BinOpNode(left, op, right);
    }
{if ("" != null) return left;}
    throw new Error("Missing return statement in function");
}

  final public Node factor() throws ParseException {Token num;
  Node expr;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INTEGER:{
      num = jj_consume_token(INTEGER);
{if ("" != null) return new IntLitNode(Integer.parseInt(num.image));}
      break;
      }
    case FLOAT_LIT:{
      num = jj_consume_token(FLOAT_LIT);
{if ("" != null) return new FloatLitNode(Float.parseFloat(num.image));}
      break;
      }
    case TRUE:{
      jj_consume_token(TRUE);
{if ("" != null) return new BoolLitNode(true);}
      break;
      }
    case FALSE:{
      jj_consume_token(FALSE);
{if ("" != null) return new BoolLitNode(false);}
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      if (jj_2_2(2)) {
        expr = appel_fonc();
{if ("" != null) return expr;}
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFIER:{
          expr = lvalue();
{if ("" != null) return expr;}
          break;
          }
        case 50:{
          jj_consume_token(50);
          expr = exp();
          jj_consume_token(51);
{if ("" != null) return expr;}
          break;
          }
        case NOT:{
          jj_consume_token(NOT);
          expr = factor();
{if ("" != null) return new UnOpNode("!", expr);}
          break;
          }
        default:
          jj_la1[20] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
}

  final public LValueNode lvalue() throws ParseException {Token id;
  Node index = null;
    id = jj_consume_token(IDENTIFIER);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 48:{
      jj_consume_token(48);
      index = exp();
      jj_consume_token(49);
      break;
      }
    default:
      jj_la1[21] = jj_gen;
      ;
    }
{if ("" != null) return new LValueNode(id.image, index);}
    throw new Error("Missing return statement in function");
}

  final public IfNode if_() throws ParseException {Node cond;
  BlockNode ifBlock, elseBlock = null;
    jj_consume_token(IF);
    jj_consume_token(50);
    cond = exp();
    jj_consume_token(51);
    ifBlock = block();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSE:{
      jj_consume_token(ELSE);
      elseBlock = block();
      break;
      }
    default:
      jj_la1[22] = jj_gen;
      ;
    }
{if ("" != null) return new IfNode(cond, ifBlock, elseBlock);}
    throw new Error("Missing return statement in function");
}

  final public WhileNode while_() throws ParseException {Node cond;
  BlockNode body;
    jj_consume_token(WHILE);
    jj_consume_token(50);
    cond = exp();
    jj_consume_token(51);
    body = block();
{if ("" != null) return new WhileNode(cond, body);}
    throw new Error("Missing return statement in function");
}

  final public ReturnNode return_() throws ParseException {Node value = null;
    jj_consume_token(RETURN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TRUE:
    case FALSE:
    case NOT:
    case IDENTIFIER:
    case INTEGER:
    case FLOAT_LIT:
    case 50:{
      value = exp();
      break;
      }
    default:
      jj_la1[23] = jj_gen;
      ;
    }
    jj_consume_token(45);
{if ("" != null) return new ReturnNode(value);}
    throw new Error("Missing return statement in function");
}

  final public PrintNode print_() throws ParseException {Node expr;
    jj_consume_token(PRINT);
    jj_consume_token(50);
    expr = exp();
    jj_consume_token(51);
{if ("" != null) return new PrintNode(expr);}
    throw new Error("Missing return statement in function");
}

  final public BlockNode block() throws ParseException {List<VarDeclNode> vars = new ArrayList<>();
  List<InstrNode> instrs = new ArrayList<>();
  VarDeclNode v;
  InstrNode i;
    jj_consume_token(46);
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT:
      case FLOAT:
      case BOOLEAN:{
        ;
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        break label_9;
      }
      v = decl_var();
vars.add(v);
    }
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF:
      case WHILE:
      case RETURN:
      case PRINT:
      case IDENTIFIER:
      case 45:
      case 46:{
        ;
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        break label_10;
      }
      i = instr();
instrs.add(i);
    }
    jj_consume_token(47);
{if ("" != null) return new BlockNode(vars, instrs);}
    throw new Error("Missing return statement in function");
}

  final public FunctionNode fonc() throws ParseException {String type;
  Token name;
  List<ParamNode> params = new ArrayList<>();
  List<VarDeclNode> vars = new ArrayList<>();
  List<InstrNode> instrs = new ArrayList<>();
  VarDeclNode v;
  InstrNode i;
    jj_consume_token(FUNC);
    type = type_();
    name = jj_consume_token(IDENTIFIER);
    jj_consume_token(50);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:
    case FLOAT:
    case BOOLEAN:{
      params = params();
      break;
      }
    default:
      jj_la1[26] = jj_gen;
      ;
    }
    jj_consume_token(51);
    jj_consume_token(46);
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT:
      case FLOAT:
      case BOOLEAN:{
        ;
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        break label_11;
      }
      v = decl_var();
vars.add(v);
    }
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF:
      case WHILE:
      case RETURN:
      case PRINT:
      case IDENTIFIER:
      case 45:
      case 46:{
        ;
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        break label_12;
      }
      i = instr();
instrs.add(i);
    }
    jj_consume_token(47);
{if ("" != null) return new FunctionNode(type, name.image, params, vars, instrs);}
    throw new Error("Missing return statement in function");
}

  final public ProcNode proc() throws ParseException {Token name;
  List<ParamNode> params = new ArrayList<>();
  List<VarDeclNode> vars = new ArrayList<>();
  List<InstrNode> instrs = new ArrayList<>();
  VarDeclNode v;
  InstrNode i;
    jj_consume_token(PROC);
    name = jj_consume_token(IDENTIFIER);
    jj_consume_token(50);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:
    case FLOAT:
    case BOOLEAN:{
      params = params();
      break;
      }
    default:
      jj_la1[29] = jj_gen;
      ;
    }
    jj_consume_token(51);
    jj_consume_token(46);
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT:
      case FLOAT:
      case BOOLEAN:{
        ;
        break;
        }
      default:
        jj_la1[30] = jj_gen;
        break label_13;
      }
      v = decl_var();
vars.add(v);
    }
    label_14:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF:
      case WHILE:
      case RETURN:
      case PRINT:
      case IDENTIFIER:
      case 45:
      case 46:{
        ;
        break;
        }
      default:
        jj_la1[31] = jj_gen;
        break label_14;
      }
      i = instr();
instrs.add(i);
    }
    jj_consume_token(47);
{if ("" != null) return new ProcNode(name.image, params, vars, instrs);}
    throw new Error("Missing return statement in function");
}

  final public List<ParamNode> params() throws ParseException {List<ParamNode> params = new ArrayList<>();
  String type;
  Token name;
    type = type_();
    name = jj_consume_token(IDENTIFIER);
params.add(new ParamNode(type, name.image));
    label_15:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 52:{
        ;
        break;
        }
      default:
        jj_la1[32] = jj_gen;
        break label_15;
      }
      jj_consume_token(52);
      type = type_();
      name = jj_consume_token(IDENTIFIER);
params.add(new ParamNode(type, name.image));
    }
{if ("" != null) return params;}
    throw new Error("Missing return statement in function");
}

  final public Node appel_fonc() throws ParseException {Token name;
  List<Node> args = new ArrayList<>();
    name = jj_consume_token(IDENTIFIER);
    jj_consume_token(50);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TRUE:
    case FALSE:
    case NOT:
    case IDENTIFIER:
    case INTEGER:
    case FLOAT_LIT:
    case 50:{
      args = arguments();
      break;
      }
    default:
      jj_la1[33] = jj_gen;
      ;
    }
    jj_consume_token(51);
{if ("" != null) return new FuncCallNode(name.image, args);}
    throw new Error("Missing return statement in function");
}

  final public InstrNode appel_proc() throws ParseException {Token name;
  List<Node> args = new ArrayList<>();
    name = jj_consume_token(IDENTIFIER);
    jj_consume_token(50);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TRUE:
    case FALSE:
    case NOT:
    case IDENTIFIER:
    case INTEGER:
    case FLOAT_LIT:
    case 50:{
      args = arguments();
      break;
      }
    default:
      jj_la1[34] = jj_gen;
      ;
    }
    jj_consume_token(51);
    jj_consume_token(45);
{if ("" != null) return new ProcCallNode(name.image, args);}
    throw new Error("Missing return statement in function");
}

  final public List<Node> arguments() throws ParseException {List<Node> args = new ArrayList<>();
  Node expr;
    expr = exp();
args.add(expr);
    label_16:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 52:{
        ;
        break;
        }
      default:
        jj_la1[35] = jj_gen;
        break label_16;
      }
      jj_consume_token(52);
      expr = exp();
args.add(expr);
    }
{if ("" != null) return args;}
    throw new Error("Missing return statement in function");
}

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_3R_assign_op_224_5_23()
 {
    if (jj_scan_token(PLUSASSIGN)) return true;
    return false;
  }

  private boolean jj_3R_lvalue_318_3_19()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_lvalue_319_5_21()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_appel_fonc_453_3_18()
 {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_assign_op_223_3_20()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_assign_op_223_3_22()) {
    jj_scanpos = xsp;
    if (jj_3R_assign_op_224_5_23()) {
    jj_scanpos = xsp;
    if (jj_3R_assign_op_225_5_24()) {
    jj_scanpos = xsp;
    if (jj_3R_assign_op_226_5_25()) {
    jj_scanpos = xsp;
    if (jj_3R_assign_op_227_5_26()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_assign_op_223_3_22()
 {
    if (jj_scan_token(ASSIGN)) return true;
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_3R_assign_213_3_17()) return true;
    return false;
  }

  private boolean jj_3_2()
 {
    if (jj_3R_appel_fonc_453_3_18()) return true;
    return false;
  }

  private boolean jj_3R_assign_213_3_17()
 {
    if (jj_3R_lvalue_318_3_19()) return true;
    if (jj_3R_assign_op_223_3_20()) return true;
    return false;
  }

  private boolean jj_3R_assign_op_227_5_26()
 {
    if (jj_scan_token(DIVASSIGN)) return true;
    return false;
  }

  private boolean jj_3R_lvalue_319_5_21()
 {
    if (jj_scan_token(48)) return true;
    return false;
  }

  private boolean jj_3R_assign_op_226_5_25()
 {
    if (jj_scan_token(MULTASSIGN)) return true;
    return false;
  }

  private boolean jj_3R_assign_op_225_5_24()
 {
    if (jj_scan_token(MINUSASSIGN)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public MiniLangParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[36];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x4,0x18,0x18,0x3800,0x3800,0x740,0x3800,0x0,0x0,0x400000,0x740,0x7c00000,0x0,0xf8000000,0xf8000000,0x60000,0x60000,0x180000,0x180000,0xc000,0x0,0x0,0x80,0xc000,0x3800,0x740,0x3800,0x3800,0x740,0x3800,0x3800,0x740,0x0,0xc000,0xc000,0x0,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x0,0x6010,0x0,0x10000,0x20,0x0,0x6010,0x0,0x4,0x1,0x1,0x0,0x0,0x0,0x0,0x60,0x40018,0x10000,0x0,0x40078,0x0,0x6010,0x0,0x0,0x6010,0x0,0x0,0x6010,0x100000,0x40078,0x40078,0x100000,};
	}
  final private JJCalls[] jj_2_rtns = new JJCalls[2];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MiniLangParser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MiniLangParser(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new MiniLangParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 36; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 36; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MiniLangParser(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new MiniLangParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 36; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new MiniLangParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 36; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MiniLangParser(MiniLangParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 36; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MiniLangParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 36; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[53];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 36; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 53; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 2; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
